swagger: '2.0'
info:
  title: Test Lambda New
  description: First test for lambda test
  version: 1.0.0
paths:
  /test:
    get:
      summary: Retrieves a list of elements
      description: |
        Gets `Element` objects.
        Optional query param of **size** determines
        size of returned array
      produces:
        - application/json
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws
        uri: 'arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:576608032189:function:getting-started-aws-cli-lamda/invocations'
        credentials: 'arn:aws:iam::576608032189:role/lambda_gateway_execution'
        httpMethod: POST
        responses:
          default:
            statusCode: '200'
      responses:
        '200':
          description: Successful response
        '400':
          description: Invalid status value
  
    
   

